openapi: 3.0.0
info:
  title: Product & Order API
  version: 1.0.0
  description: API for managing products and orders.

servers:
  - url: http://localhost:3000

paths:
  /products:
    get:
      summary: Get all products
      tags: [Products]
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error fetching products

    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProduct"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error creating product

  /products/{id}:
    put:
      summary: Update a product
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProduct"
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
        "500":
          description: Error updating product

    delete:
      summary: Delete a product and its related orders
      tags: [Products]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product deleted successfully (No Content)
        "404":
          description: Product not found
        "500":
          description: Error deleting product

  /orders:
    post:
      summary: Create a new order
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewOrder"
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Product not found
        "500":
          description: Error creating order

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string
        price:
          type: string
          example: "699.99"

    NewProduct:
      type: object
      required:
        - name
        - description
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number

    Order:
      type: object
      properties:
        id:
          type: number
        product_id:
          type: string
        quantity:
          type: number
        total_price:
          type: string

    NewOrder:
      type: object
      required:
        - product_id
        - quantity
      properties:
        product_id:
          type: number
        quantity:
          type: number
